find_path(HELLO_INCLUDE_DIR hello.h ${CMAKE_CURRENT_LIST_DIR}/include ${CMAKE_CURRENT_LIST_DIR}/include/hello)
find_library(HELLO_LIBRARY hello ${CMAKE_CURRENT_LIST_DIR}/lib)
if(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    set(HELLO_FOUND true)
endif()
if(HELLO_FOUND)
    if(NOT HELLO_FIND_QUIETLY)
        message(STATUS "Found Hello:")
        message(STATUS "    include directory: ${HELLO_INCLUDE_DIR}")
        message(STATUS "    libs             : ${HELLO_LIBRARY}")
    endif()
else()
    if(HELLO_FIND_REQUIRED)
        message(FATAL_ERROR "Could not find Hello!")
    endif()
endif()